name: Automerge

on:
  # Enabling auto-merge when a pull request is approved by spexific people (in `review-author-associations` below)
  pull_request_review:
    types:
      - submitted

  # Enabling auto-merge when PR is created by the epcific peopl from `pull-request-author-associations` below
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          merge-method: merge
          do-not-merge-labels: no-automerge
          pull-request: ${{ github.event.inputs.pull-request }}
          pull-request-author-associations: OWNER
          review-author-associations: OWNER
          dry-run: true
          review: ${{ github.event.inputs.review }}